import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Bridge,Snapshot,Workspace,Bindings,Role} from './model.ts';
import {ROLES} from './model.ts';
import {candidates} from './workspace.ts';
import {AudioPanel} from './audio-panel.tsx';
declare global{interface Window{controlCenter:Bridge}}
const api=window.controlCenter;
const labels:Record<Role,string>={intro:'Intro',main:'Main / On Air',speaker:'Speaker',bible:'Bible reading',outro:'Outro'};
const date=(s:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
function App(){
  const[s,set]=useState<Snapshot|null>(null),[tab,setTab]=useState('rehearsal'),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const[pending,setPending]=useState(false),[password,setPassword]=useState(''),[draft,setDraft]=useState<Workspace|null>(null);
  const[speaker,setSpeaker]=useState(''),[reference,setReference]=useState('Johannes Kap. 3 ab Vers 16');
  const[title,setTitle]=useState(''),[when,setWhen]=useState(''),[newSpeaker,setNewSpeaker]=useState(''),[now,setNow]=useState(Date.now());
  useEffect(()=>{void api.snapshot().then(set).catch(()=>setError('Could not connect to the application backend.'));const off=api.onState(set);const tick=setInterval(()=>setNow(Date.now()),250);return()=>{off();clearInterval(tick);};},[]);
  useEffect(()=>{if(s&&!draft)setDraft(s.workspace);},[s,draft]);
  async function act(fn:()=>Promise<unknown>){setPending(true);setError('');setNotice('');try{await fn();const latest=await api.snapshot();set(latest);setDraft(latest.workspace);}catch(e){setError((e instanceof Error?e.message:'Action failed.').replace(/^Error invoking remote method '[^']+': (?:Error: )?/,''));}finally{setPending(false);}}
  if(!s)return <main><h1>Broadcast Control Center</h1><p role="status">Starting local workspace…</p><p>{error}</p></main>;
  const w=s.workspace,r=s.runtime,t=s.transport,locked=pending||r.busy,editing=r.mode==='simulation'&&r.phase==='idle'&&!locked;
  const selected=w.services.find(x=>x.id===r.selectedService),next=selected?w.services.find(x=>x.startsAt>selected.startsAt):null;
  const remaining=r.returnAt?Math.max(0,Math.ceil((r.returnAt-now)/1000)):null;
  const count=w.inventory?.nodes.reduce((a,n)=>a+n.items.length,0)||0;
  const mute=s.serviceAudio,matched=mute?.inputName===w.bindings.audioInput;
  const muteFresh=t.connected&&matched&&mute?.phase==='confirmed'&&mute.checkedAt!==null&&now-mute.checkedAt<6000&&typeof mute.muted==='boolean';
  const muteLabel=muteFresh?(mute!.muted?'Muted — OBS confirmed':'Unmuted — OBS confirmed'):t.connected&&matched&&mute?.phase==='pending'?'Checking mute state…':'Unknown / not confirmed';
  function updateBindings(key:keyof Bindings,value:any){setDraft(d=>d?{...d,bindings:{...d.bindings,[key]:value,confirmed:false},captions:{...d.captions,confirmed:false}}:d);}
  function save(work:Workspace){return act(()=>api.saveWorkspace(work));}
  function show(role:Role){return act(()=>api.command(role,role==='speaker'?speaker:role==='bible'?reference:undefined));}
  function connectObs(){if(!draft)return;const entered=password,settings={...draft,bindings:{...draft.bindings,confirmed:false},captions:{...draft.captions,confirmed:false}};
    return act(async()=>{await api.saveWorkspace(settings);await api.inspect(entered);setPassword('');setNotice('OBS inspected. Password cleared after success.');});}
  function chooseGroup(name:string){if(!draft)return;const node=w.inventory?.nodes.find(n=>n.name===name&&n.type==='group');
    const pool=node?.items.filter(i=>i.kind?.startsWith('text_')).map(i=>i.source)||[];
    setDraft({...draft,captions:{...draft.captions,speakerGroup:name,speakerPool:pool,speakerSources:Object.fromEntries(w.speakers.map(n=>[n,pool.includes(n)?n:''])),confirmed:false}});}
  const modeLabel=r.mode==='simulation'?'SIMULATION · NO DEVICE WRITES':r.mode==='obs-preview'?'OBS PREVIEW ONLY':r.serviceAudioEnabled?'OFFLINE PROGRAM + CAPTIONS + AUDIO':'OFFLINE PROGRAM + CAPTIONS';
  const pageTitle=tab==='audio'?'Audio verification':tab==='rehearsal'?'Service rehearsal':tab==='setup'?'Connections & mappings':tab==='schedule'?'Services & speakers':'Activity log';
  return <div className="shell">
    <aside><div className="brand"><span className="brand-mark">CC</span><div>Broadcast<br/><strong>Control Center</strong></div></div>
      <div className="milestone">OFFLINE REHEARSAL · {s.version}</div>
      <nav aria-label="Main navigation">{[['rehearsal','Service rehearsal'],['audio','Audio verification'],['setup','Connections & mappings'],['schedule','Services & speakers'],['log','Activity log']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      <div className="sidebar-note"><strong>No live-stream controls</strong><p>Offline Program mode changes real OBS scenes and captions in BCC TEST. Optional service-input muting requires a separate checkbox in its confirmation dialog.</p><p>No volume, track, monitoring, streaming or hardware commands. Audio verification remains read-only.</p></div>
    </aside>
    <main><header><div><div className="eyebrow">SERVICE BROADCAST CONTROL CENTER</div><h1>{pageTitle}</h1></div><span className={`pill ${r.mode==='simulation'?'':'amber'}`}>{modeLabel}</span></header>
      <div className="health"><span className={t.connected?'good':''}>OBS {t.connected?'connected':'not connected'}</span><span>{t.streaming===true?'OBS STREAM ACTIVE':t.streaming===false?'OBS stream off':'OBS stream unknown'}</span><span>{w.inventory?`${w.inventory.scenes.length} scenes · ${count} items`:'No site profile'}</span></div>
      {error&&<div role="alert" className="alert">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
      {!!t.statusWarnings?.length&&<div id="obs-status-warnings" className="notice"><strong>OBS status notes</strong>{t.statusWarnings.map((warning,index)=><p key={index}>{warning}</p>)}<p>Unknown output states block rehearsal controls, not read-only audio observation. Explicitly absent Replay Buffer / Virtual Camera resources are distinguished from unknown states in offline Program mode. Preview-only mode keeps its stricter checks.</p></div>}
      {tab==='audio'&&<AudioPanel api={api} s={s}/>}
      {tab==='rehearsal'&&<>
        <section className="service-bar"><div><label htmlFor="service">SELECTED SERVICE · EUROPE/BERLIN</label><select id="service" disabled={locked||r.phase!=='idle'} value={r.selectedService} onChange={e=>void act(()=>api.command('select',e.target.value))}><option value="">Select a service…</option>{w.services.map(x=><option key={x.id} value={x.id}>{x.title} · {date(x.startsAt)}</option>)}</select></div><div><label>NEXT SERVICE</label><strong>{next?date(next.startsAt):'No later service scheduled'}</strong></div></section>
        {!w.services.length&&<div className="notice">Add a service in Services & speakers. Simulation works without OBS.</div>}
        <section className="stage" aria-label="Simulated program"><span className="stage-label">APP STATE — NOT THE OBS VIDEO FEED</span><div className="phase">{r.phase==='idle'?'Ready to rehearse':r.phase==='prepared'?'Service prepared':labels[r.phase]}</div><h2>{selected?.title||'A simpler Sunday workflow'}</h2><p>{r.phase==='outro'?(next?`Next service · ${date(next.startsAt)}`:'Next service not set'):r.mode==='offline-program'?'Real changes in the test collection. Watch OBS to check the picture.':'Practice the service sequence without broadcasting.'}</p>{r.overlay&&<div className="lower-third"><span>{r.phase==='speaker'?'SPEAKER':'BIBLE REFERENCE'}</span><strong>{r.overlay}</strong></div>}<span className="countdown">{remaining!==null?`Return to Main in ${remaining}s`:' '}</span></section>
        <section className="flow"><button disabled={locked||r.phase!=='idle'||!selected} onClick={()=>void act(()=>api.command('prepare'))}>1 · Prepare</button><button disabled={locked||r.phase!=='prepared'} onClick={()=>void show('intro')}>2 · Intro</button><button className="primary" disabled={locked||!['intro','main','speaker','bible'].includes(r.phase)} onClick={()=>void show('main')}>3 · Main / On Air</button><button disabled={locked||!['intro','main','speaker','bible'].includes(r.phase)} onClick={()=>void show('outro')}>4 · Outro</button></section>
        <article id="service-audio-status" aria-live="polite"><h2>Service audio · {w.bindings.audioInput||'No input selected'}</h2><strong>{muteLabel}</strong><p id="service-audio-policy">{r.serviceAudioEnabled?'Mute rules enabled for this rehearsal session.':'Mute rules off. Enable them with the checkbox in the offline Program confirmation dialog.'}</p><small>Prepare/Intro/Outro mute this input. Only Intro → Main unmutes it. Captions and all returns preserve manual mutes. This is OBS input status, not final broadcast sound.</small>{matched&&mute?.note&&<p className="hint">{mute.note}</p>}</article>
        <section className="two-col"><article><h2>Speaker</h2><select aria-label="Speaker" value={speaker} onChange={e=>setSpeaker(e.target.value)}><option value="">Select a speaker…</option>{w.speakers.map(n=><option key={n}>{n}</option>)}</select><button disabled={locked||!speaker||!['main','speaker','bible'].includes(r.phase)} onClick={()=>void show('speaker')}>Show speaker · 10 seconds</button>{r.mode==='offline-program'&&speaker&&!w.captions.speakerSources[speaker]&&<p className="notice">No OBS name source is mapped for this speaker.</p>}</article><article><h2>Bible reading</h2><input aria-label="Bible reference" value={reference} onChange={e=>setReference(e.target.value)} maxLength={500}/><button disabled={locked||!reference.trim()||!['main','speaker','bible'].includes(r.phase)} onClick={()=>void show('bible')}>Show reference · 10 seconds</button><small>Reference only. Verse validation and Bible text are not included yet.</small></article></section>
        <section className="toolbar"><button id="cancel-rehearsal" onClick={()=>void act(()=>api.command('reset'))}>Cancel / return to Simulation</button><button disabled={locked||!t.connected||!w.bindings.confirmed||r.phase!=='idle'||r.mode!=='simulation'} onClick={()=>void act(()=>api.mode('obs-preview'))}>Enable OBS Preview rehearsal…</button><button id="enable-offline" disabled={locked||!t.connected||!w.bindings.confirmed||!w.captions.confirmed||r.phase!=='idle'||r.mode!=='simulation'} onClick={()=>void act(()=>api.mode('offline-program'))}>Enable offline Program & captions…</button></section>
        <p className="hint">Simulation sends no writes. Preview-only changes Preview scenes, not captions or audio. Offline Program changes real scenes/captions; its optional checkbox enables only the selected input's mute rules. Cancel and exit do not undo completed changes.</p>
      </>}
      {tab==='setup'&&draft&&<>
        <section className="toolbar"><button disabled={!editing} className="primary" onClick={()=>void act(()=>api.importFile())}>Import report / site profile…</button><button disabled={locked} onClick={()=>void act(async()=>{setNotice(await api.exportFile());})}>Export workspace…</button></section>
        {!editing&&<p className="notice">Cancel the rehearsal and return to Simulation to edit setup.</p>}
        <section className="two-col"><article><h2>OBS</h2><label>Local WebSocket URL<input id="obs-url" value={draft.obsUrl} disabled={!editing} onChange={e=>setDraft({...draft,obsUrl:e.target.value})}/></label><label>WebSocket password<input id="obs-password" type="password" autoComplete="off" maxLength={512} value={password} onChange={e=>setPassword(e.target.value)} disabled={!editing}/></label><button id="inspect-obs" disabled={!editing} onClick={()=>void connectObs()}>Connect & inspect OBS</button><button id="clear-obs-password" disabled={!editing||!password} onClick={()=>setPassword('')}>Clear password</button><small>Password is not saved. Failed attempts retain it for retry. Successful inspection clears it.</small><p>Collection: {w.inventory?.collection||'Not inspected'}</p><p>Program: {t.program||'Unknown'} · Preview: {t.preview||'Unknown'}</p></article>
        <article><h2>Companion</h2><label>Local base URL<input value={draft.companionUrl} disabled={!editing} onChange={e=>setDraft({...draft,companionUrl:e.target.value})}/></label><button disabled={!editing} onClick={()=>void act(async()=>{await api.saveWorkspace(draft);await api.companion();})}>Inspect Companion configuration…</button><p>{s.companionResult}</p><small>Configuration is not live device health. No Companion actions run.</small>{w.connections.map((c,index)=><div className="connection" key={index}><strong>{c.label}</strong><span>{c.module} · {c.host||'No address'}<br/>Configured {c.enabled?'enabled':'disabled'} · health unknown</span></div>)}</article></section>
        <article><h2>Scene roles</h2><div className="mapping-grid">{ROLES.map(role=><label key={role}>{labels[role]}<select value={draft.bindings.scenes[role]} disabled={!editing} onChange={e=>updateBindings('scenes',{...draft.bindings.scenes,[role]:e.target.value})}><option value="">Unresolved</option>{w.inventory?.scenes.map(n=><option key={n}>{n}</option>)}</select></label>)}</div><button disabled={!editing||ROLES.some(role=>!w.inventory?.scenes.includes(draft.bindings.scenes[role]))} onClick={()=>void save({...draft,bindings:{...draft.bindings,confirmed:true}})}>Confirm scene mappings</button><span className="hint"> {w.bindings.confirmed?'Confirmed for this session':'Not confirmed'}</span></article>
        <article><h2>Caption sources</h2><p>Saving mappings makes no changes to OBS. Speaker names use the separate group mapping below.</p><div className="two-col">{([['bibleText','bible','Bible reference'],['nextServiceText','outro','Next-service text']] as const).map(([key,role,label])=><label key={key}>{label}<select disabled={!editing} value={draft.bindings[key]} onChange={e=>updateBindings(key,e.target.value)}><option value="">Unresolved</option>{[...new Set(candidates(w.inventory,draft.bindings.scenes[role]).map(x=>x.name))].map(n=><option key={n}>{n}</option>)}</select>{candidates(w.inventory,draft.bindings.scenes[role]).filter(x=>x.name===draft.bindings[key]).map((x,index)=><small key={index}>{x.path} · {x.enabled?'enabled path':'hidden path'}</small>)}</label>)}<label>Service-audio input (mute rules are opt-in)<select id="service-audio-input" value={draft.bindings.audioInput} disabled={!editing} onChange={e=>updateBindings('audioInput',e.target.value)}><option value="">Unresolved</option>{w.inventory?.inputs.filter(x=>/audio|capture|avcapture/.test(x.kind)).map(x=><option key={x.name}>{x.name}</option>)}</select><small>Only this exact input can be muted by the optional offline policy. Saving alone does not enable it.</small></label></div><button disabled={!editing} onClick={()=>void save(draft)}>Save source selections</button></article>
        <article><h2>Offline Program & speaker-name mapping</h2><p>First back up and duplicate your OBS scene collection. Name the duplicate <strong>BCC TEST</strong> (or BCC TEST - a description), select it in OBS, then connect and inspect again. Stop external encoders and disable external automation. Only OBS built-in output states are checked.</p>
          <label>Test collection<input id="test-collection" disabled={!editing} value={draft.captions.testCollection} placeholder="BCC TEST" onChange={e=>setDraft({...draft,captions:{...draft.captions,testCollection:e.target.value,confirmed:false}})}/></label>
          <label>Group containing speaker-name text sources<select id="speaker-group" disabled={!editing} value={draft.captions.speakerGroup} onChange={e=>chooseGroup(e.target.value)}><option value="">Unresolved</option>{w.inventory?.nodes.filter(n=>n.type==='group'&&n.items.some(i=>i.kind?.startsWith('text_'))).map(n=><option key={n.name}>{n.name}</option>)}</select></label>
          <p><strong>Review every name in this pool:</strong> {draft.captions.speakerPool.join(' · ')||'No group chosen'}</p><p>Only these reviewed text items are changed by speaker selection. Images, groups, media and audio are not visibility-toggled.</p>
          <div className="two-col">{w.speakers.map(n=><label key={n}>{n}<select disabled={!editing} value={draft.captions.speakerSources[n]||''} onChange={e=>setDraft({...draft,captions:{...draft.captions,speakerSources:{...draft.captions.speakerSources,[n]:e.target.value},confirmed:false}})}><option value="">No display mapped</option>{draft.captions.speakerPool.map(source=><option key={source}>{source}</option>)}</select></label>)}</div>
          <button id="confirm-captions" disabled={!editing||!draft.captions.speakerPool.length||!draft.bindings.bibleText||!draft.bindings.nextServiceText||!/^BCC TEST(?:$|[ -])/.test(draft.captions.testCollection)||draft.captions.testCollection!==w.inventory?.collection} onClick={()=>void save({...draft,bindings:{...draft.bindings,confirmed:true},captions:{...draft.captions,confirmed:true}})}>I reviewed the pool — confirm scene & caption mappings</button><p>{w.captions.confirmed?'Caption mappings confirmed for this session. Enable offline Program mode separately in Service rehearsal.':'Offline Program mode is not authorized.'}</p>
        </article>
        <article><h2>Hardware validation notes</h2><p>Metadata only; these never unlock hardware controls.</p><div className="two-col">{([['frontInput','RØDECaster input for Front'],['sideInput','RØDECaster input for Side'],['audioRoute','Broadcast-only audio route']] as const).map(([key,label])=><label key={key}>{label}<input disabled={!editing} placeholder="Unverified" value={draft.hardwareNotes[key]} onChange={e=>setDraft({...draft,hardwareNotes:{...draft.hardwareNotes,[key]:e.target.value}})}/></label>)}</div><button disabled={!editing} onClick={()=>void save(draft)}>Save validation notes</button></article>
        <article><h2>Read-only audio snapshot</h2><p>This is the last inspection, not live meters. Use Audio verification for current readings. This table sends no commands.</p><div className="table-scroll"><table><thead><tr><th>Input</th><th>Muted</th><th>Level</th><th>Tracks</th><th>Monitor</th></tr></thead><tbody>{w.inventory?.audio.map(a=><tr key={a.name}><td>{a.name}</td><td>{a.muted===null?'Unknown':a.muted?'Yes':'No'}</td><td>{a.volumeDb===null?'Unknown':`${a.volumeDb.toFixed(1)} dB`}</td><td>{Object.entries(a.tracks).filter(([,v])=>v).map(([k])=>k).join(', ')||'None / unknown'}</td><td>{a.monitor||'Unknown'}</td></tr>)}</tbody></table></div></article>
        <article><h2>Scene and group inspector</h2><p>{w.inventory?.origin==='live'?'Captured from OBS in this session.':'Saved observation; reconnect before enabling controls.'}</p>{w.inventory?.warnings.map((warning,index)=><p className="notice" key={index}>{warning}</p>)}{w.inventory?.nodes.map(n=><details key={n.name}><summary>{n.name} <span className="hint">{n.type} · {n.items.length} items</span></summary>{n.warnings.map((x,index)=><p key={index}>{x}</p>)}{n.items.map((i,index)=><div key={index} className="tree-item"><span>{i.enabled?'●':'○'}</span><strong>{i.source}</strong><span>{i.group?'group':i.container?'scene':i.kind} · item {i.id}</span></div>)}</details>)}</article>
      </>}
      {tab==='schedule'&&<>
        <p className="notice">Local schedule only; no YouTube events are created. Display timezone: Europe/Berlin.</p>
        <section className="two-col"><article><h2>Add a service</h2><label>Title<input value={title} maxLength={240} disabled={!editing} onChange={e=>setTitle(e.target.value)}/></label><label>Start date & time (this Mac’s timezone)<input type="datetime-local" value={when} disabled={!editing} onChange={e=>setWhen(e.target.value)}/></label><button disabled={!editing||!title.trim()||!when} onClick={()=>void act(async()=>{await api.saveWorkspace({...w,services:[...w.services,{id:crypto.randomUUID(),title:title.trim(),startsAt:new Date(when).toISOString()}]});setTitle('');setWhen('');})}>Add service</button></article><article><h2>Add a speaker</h2><label>Display name<input value={newSpeaker} maxLength={240} disabled={!editing} onChange={e=>setNewSpeaker(e.target.value)}/></label><button disabled={!editing||!newSpeaker.trim()} onClick={()=>void act(async()=>{await api.saveWorkspace({...w,speakers:[...w.speakers,newSpeaker.trim()],captions:{...w.captions,confirmed:false}});setNewSpeaker('');})}>Add speaker</button>{w.speakers.map(n=><div className="list-row" key={n}><span>{n}</span><button disabled={!editing} aria-label={`Remove speaker ${n}`} onClick={()=>void save({...w,speakers:w.speakers.filter(x=>x!==n),captions:{...w.captions,confirmed:false}})}>Remove</button></div>)}</article></section>
        <article><h2>Scheduled services</h2>{w.services.map(x=><div className="list-row" key={x.id}><div><strong>{x.title}</strong><p>{date(x.startsAt)}</p></div><button disabled={!editing} onClick={()=>void save({...w,services:w.services.filter(y=>y.id!==x.id)})}>Remove</button></div>)}{!w.services.length&&<p>No services yet.</p>}</article>
      </>}
      {tab==='log'&&<article><h2>Session activity</h2><p>Closing or cancelling stops pending commands, not OBS outputs. Completed test-collection and mute edits remain.</p>{r.events.map((e,index)=><div className="list-row" key={index}><time>{new Date(e.at).toLocaleTimeString()}</time><span>{e.message}</span></div>)}{!r.events.length&&<p>No actions in this session.</p>}</article>}
      <footer>OFFLINE TEST MILESTONE · No YouTube or hardware commands · Existing Stream Deck remains independent</footer>
    </main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
