import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Bridge,Snapshot,Workspace,Bindings,Role} from './model.ts';
import {ROLES} from './model.ts';
import {candidates} from './workspace.ts';
declare global {interface Window {controlCenter:Bridge}}
const api=window.controlCenter;
const labels:Record<Role,string>={intro:'Intro',main:'Main / On Air',speaker:'Speaker',bible:'Bible reading',outro:'Outro'};
const date=(s:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
function App(){
  const [s,set]=useState<Snapshot|null>(null),[tab,setTab]=useState('rehearsal'),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [pending,setPending]=useState(false),[password,setPassword]=useState(''),[draft,setDraft]=useState<Workspace|null>(null);
  const [speaker,setSpeaker]=useState(''),[reference,setReference]=useState('Johannes Kap. 3 ab Vers 16');
  const [title,setTitle]=useState(''),[when,setWhen]=useState(''),[newSpeaker,setNewSpeaker]=useState(''),[now,setNow]=useState(Date.now());
  useEffect(()=>{void api.snapshot().then(set).catch(()=>setError('Could not connect to the application backend.'));const off=api.onState(set);const tick=setInterval(()=>setNow(Date.now()),250);return()=>{off();clearInterval(tick);};},[]);
  useEffect(()=>{if(s && !draft)setDraft(s.workspace);},[s,draft]);
  async function act(fn:()=>Promise<unknown>){setPending(true);setError('');setNotice('');try{await fn();const latest=await api.snapshot();set(latest);setDraft(latest.workspace);}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setPending(false);}}
  if(!s)return <main><h1>Broadcast Control Center</h1><p role="status">Starting local workspace…</p><p>{error}</p></main>;
  const w=s.workspace,r=s.runtime,t=s.transport;
  const locked=pending || r.busy;
  const editing=r.mode==='simulation' && r.phase==='idle' && !locked;
  const selected=w.services.find(x=>x.id===r.selectedService);
  const next=selected?w.services.find(x=>x.startsAt>selected.startsAt):null;
  const confirmed=w.bindings.confirmed;
  const remaining=r.returnAt?Math.max(0,Math.ceil((r.returnAt-now)/1000)):null;
  const count=w.inventory?.nodes.reduce((a,n)=>a+n.items.length,0)||0;
  function updateBindings(key:keyof Bindings,value:any){setDraft(d=>d?{...d,bindings:{...d.bindings,[key]:value,confirmed:false}}:d);}
  function save(nextWorkspace:Workspace){return act(()=>api.saveWorkspace(nextWorkspace));}
  function show(role:Role){return act(()=>api.command(role,role==='speaker'?speaker:role==='bible'?reference:undefined));}
  return <div className="shell">
    <aside><div className="brand"><span className="brand-mark">CC</span><div>Broadcast<br/><strong>Control Center</strong></div></div>
      <div className="milestone">SETUP & REHEARSAL · {s.version}</div>
      <nav aria-label="Main navigation">{[['rehearsal','Service rehearsal'],['setup','Connections & mappings'],['schedule','Services & speakers'],['log','Activity log']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      <div className="sidebar-note"><strong>No live-broadcast controls</strong><p>Streaming, camera movement, switching hardware and audio writes are unavailable in this milestone.</p><p>Site data stays on this Mac. Importing a file never runs its commands.</p></div>
    </aside>
    <main><header><div><div className="eyebrow">SERVICE BROADCAST CONTROL CENTER</div><h1>{tab==='rehearsal'?'Service rehearsal':tab==='setup'?'Connections & mappings':tab==='schedule'?'Services & speakers':'Activity log'}</h1></div><span className={`pill ${r.mode==='simulation'?'':'amber'}`}>{r.mode==='simulation'?'SIMULATION · NO DEVICE WRITES':'OBS PREVIEW ONLY'}</span></header>
      <div className="health"><span className={t.connected?'good':''}>OBS {t.connected?'connected':'not connected'}</span><span>{t.streaming===true?'OBS STREAM ACTIVE':t.streaming===false?'OBS stream off':'OBS stream unknown'}</span><span>{w.inventory?`${w.inventory.scenes.length} scenes · ${count} items`:'No site profile'}</span></div>
      {error && <div role="alert" className="alert">{error}</div>}{notice && <div role="status" className="notice">{notice}</div>}
      {tab==='rehearsal' && <>
        <section className="service-bar"><div><label htmlFor="service">SELECTED SERVICE · EUROPE/BERLIN</label><select id="service" disabled={locked || r.phase!=='idle'} value={r.selectedService} onChange={e=>void act(()=>api.command('select',e.target.value))}><option value="">Select a service…</option>{w.services.map(x=><option key={x.id} value={x.id}>{x.title} · {date(x.startsAt)}</option>)}</select></div><div><label>NEXT SERVICE</label><strong>{next?date(next.startsAt):'No later service scheduled'}</strong></div></section>
        {!w.services.length && <div className="notice">Add a service in Services & speakers to begin. Simulation works without OBS.</div>}
        <section className="stage" aria-label="Simulated program"><span className="stage-label">APP SIMULATION — NOT THE OBS VIDEO FEED</span><div className="phase">{r.phase==='idle'?'Ready to rehearse':r.phase==='prepared'?'Service prepared':labels[r.phase]}</div><h2>{selected?.title || 'A simpler Sunday workflow'}</h2><p>{r.phase==='outro'?(next?`Next service · ${date(next.startsAt)}`:'Next service not set'):'Practice the service sequence without broadcasting.'}</p>{r.overlay && <div className="lower-third"><span>{r.phase==='speaker'?'SPEAKER':'BIBLE REFERENCE'}</span><strong>{r.overlay}</strong></div>}<span className="countdown">{remaining!==null?`Return to Main in ${remaining}s`:' '}</span></section>
        <section className="flow"><button disabled={locked || r.phase!=='idle' || !selected} onClick={()=>void act(()=>api.command('prepare'))}>1 · Prepare</button><button disabled={locked || r.phase!=='prepared'} onClick={()=>void show('intro')}>2 · Intro</button><button className="primary" disabled={locked || !['intro','main','speaker','bible'].includes(r.phase)} onClick={()=>void show('main')}>3 · Main / On Air</button><button disabled={locked || !['intro','main','speaker','bible'].includes(r.phase)} onClick={()=>void show('outro')}>4 · Outro</button></section>
        <section className="two-col"><article><h2>Speaker</h2><select aria-label="Speaker" value={speaker} onChange={e=>setSpeaker(e.target.value)}><option value="">Select a speaker…</option>{w.speakers.map(n=><option key={n}>{n}</option>)}</select><button disabled={locked || !speaker || !['main','speaker','bible'].includes(r.phase)} onClick={()=>void show('speaker')}>Show speaker · 10 seconds</button></article><article><h2>Bible reading</h2><input aria-label="Bible reference" value={reference} onChange={e=>setReference(e.target.value)} maxLength={500}/><button disabled={locked || !reference.trim() || !['main','speaker','bible'].includes(r.phase)} onClick={()=>void show('bible')}>Show reference · 10 seconds</button><small>Reference only; Bible text and verse validation are not included yet.</small></article></section>
        <section className="toolbar"><button disabled={locked} onClick={()=>void act(()=>api.command('reset'))}>Reset / cancel timed return</button><button disabled={locked || !t.connected || !confirmed || r.phase!=='idle'} onClick={()=>void act(()=>api.mode(r.mode==='simulation'?'obs-preview':'simulation'))}>{r.mode==='simulation'?'Enable OBS Preview rehearsal…':'Return to simulation'}</button></section>
        <p className="hint">In OBS Preview mode, only the mapped scene changes. Names and references above remain simulated; this build does not edit OBS text or visibility. Disable external auto-transitions before testing.</p>
      </>}
      {tab==='setup' && draft && <>
        <section className="toolbar"><button disabled={!editing} className="primary" onClick={()=>void act(()=>api.importFile())}>Import report / site profile…</button><button disabled={locked} onClick={()=>void act(async()=>{setNotice(await api.exportFile());})}>Export workspace…</button></section>
        {!editing && <p className="notice">Reset to simulation to edit connections or mappings.</p>}
        <section className="two-col"><article><h2>OBS</h2><label>Local WebSocket URL<input value={draft.obsUrl} disabled={!editing} onChange={e=>setDraft({...draft,obsUrl:e.target.value})}/></label><label>WebSocket password<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} disabled={!editing}/></label><button disabled={!editing} onClick={()=>void act(async()=>{await api.saveWorkspace(draft);const p=password;setPassword('');await api.inspect(p);})}>Connect & inspect OBS</button><small>Password is not saved. Inspection does not change scenes or settings.</small><p>Collection: {w.inventory?.collection || 'Not inspected'}</p><p>Program: {t.program || 'Unknown'} · Preview: {t.preview || 'Unknown'}</p></article>
        <article><h2>Companion</h2><label>Local base URL<input value={draft.companionUrl} disabled={!editing} onChange={e=>setDraft({...draft,companionUrl:e.target.value})}/></label><button disabled={!editing} onClick={()=>void act(async()=>{await api.saveWorkspace(draft);await api.companion();})}>Inspect Companion configuration…</button><p>{s.companionResult}</p><small>A configuration export does not verify device health. No Companion actions are executed.</small>{w.connections.map((c,index)=><div className="connection" key={index}><strong>{c.label}</strong><span>{c.module} · {c.host || 'No address'}<br/>Configured {c.enabled?'enabled':'disabled'} · health unknown</span></div>)}</article></section>
        <article><h2>Scene roles</h2><p>Choose and confirm all five mappings. Importing a report never confirms them automatically.</p><div className="mapping-grid">{ROLES.map(role=><label key={role}>{labels[role]}<select value={draft.bindings.scenes[role]} disabled={!editing} onChange={e=>updateBindings('scenes',{...draft.bindings.scenes,[role]:e.target.value})}><option value="">Unresolved</option>{w.inventory?.scenes.map(n=><option key={n}>{n}</option>)}</select></label>)}</div><button disabled={!editing || ROLES.some(role=>!w.inventory?.scenes.includes(draft.bindings.scenes[role]))} onClick={()=>void save({...draft,bindings:{...draft.bindings,confirmed:true}})}>Confirm scene mappings</button><span className="hint"> {confirmed?'Confirmed for this session':'Not confirmed'}</span></article>
        <article><h2>Source mappings — saved for later control</h2><p>These selections are metadata only. Nothing here changes an OBS source.</p><div className="two-col">{([['speakerText','speaker','Speaker text'],['bibleText','bible','Bible reference'],['nextServiceText','outro','Next-service text']] as const).map(([key,role,label])=><label key={key}>{label}<select disabled={!editing} value={draft.bindings[key]} onChange={e=>updateBindings(key,e.target.value)}><option value="">Unresolved</option>{[...new Set(candidates(w.inventory,draft.bindings.scenes[role]).map(x=>x.name))].map(n=><option key={n}>{n}</option>)}</select>{candidates(w.inventory,draft.bindings.scenes[role]).filter(x=>x.name===draft.bindings[key]).map((x,index)=><small key={index}>{x.path} · {x.enabled?'enabled path':'hidden path'}</small>)}</label>)}<label>Broadcast-audio candidate<select value={draft.bindings.audioInput} disabled={!editing} onChange={e=>updateBindings('audioInput',e.target.value)}><option value="">Unresolved</option>{w.inventory?.inputs.filter(x=>/audio|capture|avcapture/.test(x.kind)).map(x=><option key={x.name}>{x.name}</option>)}</select><small>Source presence does not establish the physical route or broadcast-only muting.</small></label></div><button disabled={!editing} onClick={()=>void save(draft)}>Save source selections</button></article>
        <article><h2>Hardware validation notes</h2><p>Record what you verify manually. These notes never unlock hardware control.</p><div className="two-col">{([['frontInput','RØDECaster input for Front'],['sideInput','RØDECaster input for Side'],['audioRoute','Broadcast-only audio route']] as const).map(([key,label])=><label key={key}>{label}<input placeholder="Unverified" disabled={!editing} value={draft.hardwareNotes[key]} onChange={e=>setDraft({...draft,hardwareNotes:{...draft.hardwareNotes,[key]:e.target.value}})}/></label>)}</div><button disabled={!editing} onClick={()=>void save(draft)}>Save validation notes</button></article>
        <article><h2>Read-only audio snapshot</h2><p>Snapshot only, not a level meter or a routing guarantee. No mute, fader or track changes are available.</p>{!w.inventory?.audio.length?<p>Connect & inspect OBS to read audio-capable inputs.</p>:<div className="table-scroll"><table><thead><tr><th>Input</th><th>Muted</th><th>Level</th><th>Tracks</th><th>Monitor</th></tr></thead><tbody>{w.inventory.audio.map(a=><tr key={a.name}><td>{a.name}</td><td>{a.muted===null?'Unknown':a.muted?'Yes':'No'}</td><td>{a.volumeDb===null?'Unknown':`${a.volumeDb.toFixed(1)} dB`}</td><td>{Object.entries(a.tracks).filter(([,v])=>v).map(([k])=>k).join(', ')||'None / unknown'}</td><td>{a.monitor||'Unknown'}</td></tr>)}</tbody></table></div>}</article>
        <article><h2>Scene and group inspector</h2><p>{w.inventory?.origin==='live'?'Captured from OBS in this session.':'Imported snapshot; nested containers may still be unresolved.'}</p>{w.inventory?.warnings.map((warning,index)=><p className="notice" key={index}>{warning}</p>)}{w.inventory?.nodes.map(n=><details key={n.name}><summary>{n.name} <span className="hint">{n.type} · {n.items.length} items</span></summary>{n.warnings.map((x,index)=><p key={index}>{x}</p>)}{n.items.map((i,index)=><div key={index} className="tree-item"><span>{i.enabled?'●':'○'}</span><strong>{i.source}</strong><span>{i.group?'group':i.container?'scene':i.kind} · item {i.id}</span></div>)}</details>)}</article>
      </>}
      {tab==='schedule' && <>
        <p className="notice">Local schedule only. No YouTube events are created. Times below are displayed in Europe/Berlin.</p>
        {!editing && <p>Reset the rehearsal before editing the schedule.</p>}
        <section className="two-col"><article><h2>Add a service</h2><label>Title<input value={title} maxLength={240} disabled={!editing} onChange={e=>setTitle(e.target.value)}/></label><label>Start date & time (this Mac’s timezone)<input type="datetime-local" value={when} disabled={!editing} onChange={e=>setWhen(e.target.value)}/></label><button disabled={!editing || !title.trim() || !when} onClick={()=>void act(async()=>{await api.saveWorkspace({...w,services:[...w.services,{id:crypto.randomUUID(),title:title.trim(),startsAt:new Date(when).toISOString()}]});setTitle('');setWhen('');})}>Add service</button></article><article><h2>Add a speaker</h2><label>Display name<input value={newSpeaker} maxLength={240} disabled={!editing} onChange={e=>setNewSpeaker(e.target.value)}/></label><button disabled={!editing || !newSpeaker.trim()} onClick={()=>void act(async()=>{await api.saveWorkspace({...w,speakers:[...w.speakers,newSpeaker.trim()]});setNewSpeaker('');})}>Add speaker</button>{w.speakers.map(n=><div className="list-row" key={n}><span>{n}</span><button disabled={!editing} aria-label={`Remove speaker ${n}`} onClick={()=>void save({...w,speakers:w.speakers.filter(x=>x!==n)})}>Remove</button></div>)}</article></section>
        <article><h2>Scheduled services</h2>{w.services.map(x=><div className="list-row" key={x.id}><div><strong>{x.title}</strong><p>{date(x.startsAt)}</p></div><button disabled={!editing} onClick={()=>void save({...w,services:w.services.filter(y=>y.id!==x.id)})}>Remove</button></div>)}{!w.services.length && <p>No services yet.</p>}</article>
      </>}
      {tab==='log' && <article><h2>Session activity</h2><p>Reloading the interface preserves this session. Closing the app cancels timers; it never stops OBS or changes audio.</p>{r.events.map((e,index)=><div className="list-row" key={index}><time>{new Date(e.at).toLocaleTimeString()}</time><span>{e.message}</span></div>)}{!r.events.length && <p>No actions in this session.</p>}</article>}
      <footer>PREVIEW MILESTONE · Local-first · No YouTube or hardware write commands · Existing Stream Deck remains independent</footer>
    </main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
